### ISSUE TITLE
getting started instructions for Linux doesn't work that well

### ISSUE THREAD

**Issue by mattvenn** [NyanCAD/Mosaic#100]
did the download, install but then jupyter mosiac failed like this

![image](https://user-images.githubusercontent.com/634220/172852897-91641019-f47d-408d-8a52-5c3ca30a9419.png)

**Comment by pepijndevos** [comment]
Try without the slash at the end

**Comment by mattvenn** [comment]
![image](https://user-images.githubusercontent.com/634220/172853895-cbb26468-5884-4b29-92d4-f312001924e2.png)
