### ISSUE TITLE
More freedom to transistor parameters

### ISSUE THREAD

**Issue by ArthurAdmiraal** [NyanCAD/Mosaic#13]
- [x] Accept text input for spice parameters like `{W_in}`
- [x] Make identifier user-edditable (so the user can specify `Min_p` instead of `nmos26`)
- [x] Add M-factor / number of fingers parameter

**Comment by pepijndevos** [comment]
Also... Sky130 mosfet is actually a subcircuit, so that will need some hack. Proper support would probably let the model specify the spice output.
