### ISSUE TITLE
Assure panels scroll with too much content

### ISSUE THREAD

**Issue by pepijndevos** [NyanCAD/Mosaic#32]

**Comment by jellebakker96** [comment]
![image](https://user-images.githubusercontent.com/35449392/162681268-9dd00246-0c74-4e09-9790-ef946c98221b.png)

Side bar does not seem to become shorter when the browser is made smaller such that the bottom options are hidden.

**Comment by pepijndevos** [comment]
Nothing is infinitely scalable, but it should work for any reasonable screen size
