### ISSUE TITLE
Make color order consistent

### ISSUE THREAD

**Issue by jellebakker96** [NyanCAD/Mosaic#77]
I would have thought that the color of the last added component should be on top when it is placed right next to another component but this seems to not be the case. I do not know how the color order is determined right now, but to me it seems inconsistent.

**Comment by pepijndevos** [comment]
???????

**Comment by jellebakker96** [comment]
![image](https://user-images.githubusercontent.com/35449392/162700144-b1426652-5cb7-4066-9baa-29be1243ac51.png)

I would have thought that the order in which you place components changes which color is on top. This does not seem to be the case. How did you determine which color is on top?

**Comment by jellebakker96** [comment]
If you place three capacitors with one cell empty in between them and then place nmos in those empty cells some of the blue is above and some of it is below the green from the capacitors

**Comment by pepijndevos** [comment]
Whatever order they are drawn in, which is whatever order they are in the map, which is arbitrary, so order is arbitrary and this is not going to change any time soon.

**Comment by jellebakker96** [comment]
Ok
