### ISSUE TITLE
It is possible to make a new schematic with a cell name from an other library

### ISSUE THREAD

**Issue by jellebakker96** [NyanCAD/Mosaic#83]

**Comment by pepijndevos** [comment]
Libraries are currently fully isolated. This will possibly change after #57

**Comment by jellebakker96** [comment]
That was not what I meant.

![signal-2022-05-07-142202_001](https://user-images.githubusercontent.com/35449392/167590483-4a7ca4b3-e6cd-4e46-b9e5-30d18bdc5989.png)
Here oscillator is a cell name from the jelle library.
