### ISSUE TITLE
GND net is not named GND in plot legend

### ISSUE THREAD

**Issue by jellebakker96** [NyanCAD/Mosaic#89]

**Comment by pepijndevos** [comment]
What do you mean? GND is always 0, you can't even plot it.

**Comment by jellebakker96** [comment]
![image](https://user-images.githubusercontent.com/35449392/167311085-afbc7e64-5c9e-483f-9e7a-921f7967d84b.png)

I thought that vv1... net was GND. I expected to see only 1 net, not 2.

**Comment by pepijndevos** [comment]
it's the branch current through the v1 voltage source.
